# Token的有效期在java.com.teee.utils.JWT类中的EXP字段设置，默认为15天
server:
  port: 8080
spring:
  main:
    allow-circular-references: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.223.187.100:3306/TEEE_DB_Dev
    username: TEEE
    password: teee123456
path:
  pic:
    works: D:/testpic/
    faces: D:/testFace/
    avatars: D:/testAvatar/
  file:
    files: D:/testfile/
    temps: D:/testTemp/
Tencent:
  token: eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFMyNTYifQ.eyJzZWNyZXRJZCI6IkFLSURqVTZaTXhXaW9va2FMelhqcnNqUHRBSUczaEVib3BXRSIsInNlY3JldEtleSI6ImdIaTVMUXdLV2JUQWgzREQyWXRBRkF2WTVSY2RWQmkzIiwiZXhwIjoxMDMxNDU3NjMyNiwianRpIjoiM2QyOWU5MWYtZjQxZS00NTE1LWI0MmUtYTk2OTM1ZDM4YTE3In0.7xkfCZvfqeG5Y-dpiMpONvSRndtZRzKO04TYbt_svdY